<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbpro-dejuan.lan" name="testcases.Dev1077CheckBuyNowPrices" tests="2" failures="1" timestamp="21 Aug 2016 08:13:48 GMT" time="147.017" errors="0">
  <testcase name="steps1" time="78.267" classname="testcases.Dev1077CheckBuyNowPrices">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1.575,01] but found [1.575,00],
	expected [1.575,01] but found [1.575,00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [1.575,01] but found [1.575,00],
	expected [1.575,01] but found [1.575,00]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.Dev1077CheckBuyNowPrices.steps1(Dev1077CheckBuyNowPrices.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- steps1 -->
  <testcase name="steps1" time="68.750" classname="testcases.Dev1077CheckBuyNowPrices"/>
</testsuite> <!-- testcases.Dev1077CheckBuyNowPrices -->
